---
title: "Git Notes"
author: "Aiden Quisenberry (PID:A19083329)"
format: html
---

## Basics of using git

Git is a distributed version control system (DVCS) that is very popular.

The core steps to using git involve 

1. Initiate a git repository
    In RStudio we just click a little radio button on project creation the command line we type:
    `git init`
    
2. Do your normal work
    Add files
    Modify ffiles etc.
    
3. Add your important files to the "stage" 
    In RStudio we click the "stage" radio button
    `git add yourfilename`
    
4. Commit your staged files to the repository
    In RStudio you just hit the "Commit" button and add a msg
    `git commit - m "your wee msg"`
    
  
You can check your project "history" and status
  `git status`
  `git log` (push Q to exit)
  
5. Git Push to sync changes TO GitHub
    the Up arrow in RStudio
    `git push`
    
6. Git Pull to sync FROM GitHub
    The Down arrow in RStudio
    `git pull`
    
You can check you project "history" and status
    `git status`